# Generated by Django 6.0.3 on 2026-06-19 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technique',
            options={'ordering': ['name'], 'verbose_name': 'Technique', 'verbose_name_plural': 'Techniques'},
        ),
        migrations.AlterModelOptions(
            name='techniquestat',
            options={'ordering': ['technique__name'], 'verbose_name': 'Technique stat', 'verbose_name_plural': 'Technique stats'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterField(
            model_name='techniquestat',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='techniquestat',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_stats', to='app.technique'),
        ),
        migrations.AlterField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
