# Generated by Django 6.0.3 on 2026-06-19 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_technique_options_alter_techniquestat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(default='Trénink', max_length=120),
        ),
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('win', 'Výhra'), ('loss', 'Prohra')], max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.technique')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.training')),
            ],
            options={
                'verbose_name': 'Training result',
                'verbose_name_plural': 'Training results',
                'ordering': ['result_type', 'technique__name'],
            },
        ),
    ]
